### ISSUE TITLE
[1.0draft] Unity special file name like `.foo` may disallowed for material and blendshape name

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm-specification#53]
https://github.com/vrm-c/vrm-specification/blob/ccbe213ed958f81fd405d87ab03e54bac7c940d6/specification/VRMC_vrm-1.0_draft/README.md#naming-restrictions
> Use characters that can be used for the file name

I think Unity special file name like `.foo` may disallowed for material name. Because I think that specification for unpacking files in Unity's Asset folder. 

See https://docs.unity3d.com/2018.4/Documentation/Manual/SpecialFolders.html

**Comment by saturday06** [comment]
No problem if Unity implementation correctly escapes those filenames to fit Unity special naming rules.

**Comment by iCyP** [comment]
I think this problem should be handled by unity implementation.
Because, I think other engines (e.g. UE, three-js, and so on) have same problem, and cover all engines reserved words is very difficult.
So, I think name limitation will cover operation system's special chars(?><\ \n...) and reserved words(like windows god mode folder name) and generally programming special meaning chars(like \0, \t, etc...). 

ref : #40

**Comment by ousttrue** [comment]
Aggregate name escape related issues.
Duplicate of #40

**Comment by saturday06** [comment]
roger
